server.port=8013
management.server.port=8013

#######################################
#	Database
#######################################
spring.data.mongodb.uri=mongodb://localhost:27888
spring.data.mongodb.database=FSE_GTW
#######################################
#  KAFKA 
#######################################
####KAFKA CONNECTION SETTINGS ##########
kafka.bootstrap-servers=localhost:29092
kafka.properties.security.protocol=PLAINTEXT
kafka.properties.sasl.mechanism=PLAINTEXT
kafka.properties.sasl.jaas.config=PLAINTEXT
kafka.properties.ssl.truststore.location=PLAINTEXT
kafka.properties.ssl.truststore.password=PLAINTEXT
kafka.oauth.tenantId=
kafka.oauth.appId=
kafka.oauth.pfxPathName=
kafka.oauth.pwd=
####### LOGGING OUTPUT FORMAT ############
# Must be one of console, json
#######################################
log.output.format=console
log.level=trace

#######################################
#  Scheduler
#######################################
scheduler.tx-scheduler=0 */1 * * * *

##################################
# Microservices
##################################
ms.url.eds-broker=http://localhost:9009
ms.url.gtw-config=http://localhost:8018
ms.url.eds-client=http://localhost:8021

########OPENTELEMETRY################################
otel.traces.exporter=logging
otel.logs.exporter=none
otel.metrics.exporter=none

otel.propagators=tracecontext,baggage